### ISSUE TITLE
Load images from binary string

### ISSUE THREAD

**Issue by kisPocok** [ksubileau/color-thief-php#21]
Hi Devs,

I would like to use Color-Thief to analyse image colors. My pictures are based on remote CDN(s) furthermore a few of them are protected. So I can't reach them with `getImageSize`. I am able to grab them with CURL, but I don't want to copy-paste them.

**It would be nice if I can load images from binary string.**

It's hard to extend the whole codebase, because `ImageLoader` functions are protected and hardcoded into the logic. 

What do you think?

**Comment by kisPocok** [comment]
Example code:

```
// Get the image binary with CURL
$curl = curl_init($image_url);
curl_setopt($curl, CURLOPT_HEADER, 0);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($curl, CURLOPT_BINARYTRANSFER, 1);
$binaryImage = curl_exec($curl);
curl_close ($curl);
```

For example in `GDImageAdapter:18` instead of using `@getImageSize` to determinate image type I would use `getImageSizeFromString($binaryImage);`.

**Comment by ksubileau** [comment]
Hi,
With the current architecture, I think the solution is to add a `loadFromString` method in the `ColorThief\Image\Adapter\IImageAdapter` interface and its implementations, and then adjust the `ImageLoader::load($source)` method so that it can detect that the `$source` is a binary string and call the `loadFromString` method of the appropriate `ImageAdapter`.

But if you have some architecture improvements to suggest, feel free ! I just want to keep as much as possible a simple API with only one or two methods and a few parameters available in the main class, so that this library remain simple to use.

**Comment by ksubileau** [comment]
Done !
Thank you for your suggestion :)
