### ISSUE TITLE
getColor() internally gets a palette of 5 colors.

### ISSUE THREAD

**Issue by tigerstrikemedia** [ksubileau/color-thief-php#23]
Is there a good reason that the `getColor()` function internally gets a 5 color pallette before simply returning the first one?

```
$palette = static::getPalette($sourceImage, 5, $quality, $area);
```

**Comment by ksubileau** [comment]
Uh... it's implemented like that in [the original Javascript version](https://github.com/lokesh/color-thief/blob/de968be81645760f54a0358fb3a442f13adf2b38/src/color-thief.js#L74), so I kept it as is to maintain consistent results. If you change this number, the final result will differ because of averagings.

But I don't really know why five and not one or anything else. I guess it's more or less an arbitrary choice, perhaps because if it calculates directly a single color, it gives more an average color than a dominant one.

If you want a more in-depth response, maybe you should ask this to [the original author](https://github.com/lokesh/color-thief) :)

**Comment by tigerstrikemedia** [comment]
@ksubileau 

Thank you for the prompt informative response ;) that makes a lot of sense.
