### ISSUE TITLE
How can I can install without composer?

### ISSUE THREAD

**Issue by Nullmegh** [ksubileau/color-thief-php#29]

**Comment by ksubileau** [comment]
You have to require each PHP files present under the _lib_ folder, one by one. The order is important, but I don't know it, sorry. You have to proceed by trial/error to find it.

Otherwise, you can write a PSR-0 autoloader. See also [this thread](http://stackoverflow.com/a/22424281) on StackOverflow.

**Comment by Nullmegh** [comment]
oh okay damm it xD

**Comment by leehoss** [comment]
Here you go....

require_once 'lib/ColorThief/ColorThief.php' ;
require_once 'lib/ColorThief/VBox.php' ;
require_once 'lib/ColorThief/PQueue.php' ;
require_once 'lib/ColorThief/CMap.php' ;

require_once 'lib/ColorThief/Image/ImageLoader.php' ;

require_once 'lib/ColorThief/Image/Adapter/IImageAdapter.php' ;
require_once 'lib/ColorThief/Image/Adapter/ImageAdapter.php' ;
require_once 'lib/ColorThief/Image/Adapter/ImagickImageAdapter.php' ;

**Comment by ksubileau** [comment]
You can also use any existing PSR-4 autoloader or implement your custom one. See https://www.php-fig.org/psr/psr-4/.
