### ISSUE TITLE
Transparent or blank images

### ISSUE THREAD

**Issue by Marchrius** [ksubileau/color-thief-php#34]
Is correct to throw an error if the image is transparent or blank?

Why cannot return an empty array instead of throwing an error?

**Comment by ksubileau** [comment]
Since a white or transparent image is an edge case for this library, I think an exception is an appropriate way to inform the calling code about that. This provides a clear information that allows the calling code to accuratly identify this situation and process it appropriately, whereas an empty table gives no clue about what happened and may be more confusing.

But do you have any counter-arguments or pros/cons to add for each solutions?

**Comment by Marchrius** [comment]
As a "human", if there are no color I'm expecting an empty array, If my image is not valid I'm expecting an exception.
As a programmer, I'm agree with you.

**Comment by ksubileau** [comment]
In my opinion, this is the responsibility of the calling code to format and present the result depending on its usage.
Right now, I don't see any real gain in changing this behavior, so I think I'll keep it as is.

Thank you for your suggestion ;)
