### ISSUE TITLE
dominant color is not in palette ?

### ISSUE THREAD

**Issue by guldil** [ksubileau/color-thief-php#57]
Hello,

I don't know if it's an issue or not, but on some image, the dominantColor is not in the palette.

In the samples from http://www.kevinsubileau.fr/projets/color-thief-php we can see it.

Is the dominant colour just the result of an analysis?

Thanks

Guldil

**Comment by romanzks** [comment]
I noticed that it depends on the number of colors in the palette. For example, in a set of 5 palette colors, the dominant color will always be the first in the set.

**Comment by araeubig** [comment]
For me i made a workaround to query both: the dominant color and the palette - this results in more computing time, but i have both. i think it would be great to query the palette and including the dominant color with "dominat = true" to have the dominant color at the first place of the array and this would reduce the overall computing time perhaps.

**Comment by ksubileau** [comment]
This behavior is intended and inherent to the way the algorithm used by the library works, the _Median Cut algorithm_. 

**Depending on the number of colors requested for the palette, you won't get the same result** because the algorithm seeks to ensure that the set of colors returned in the palette is representative of all the original colors in the image. This is not a simple sort where the first N elements are taken, but rather a slicing into N parts where each part represents a subset of all the colours present in the source image. Consequently, if you change the number of colours in the palette, you change the number of parts (N) and therefore the final result.

**For a single dominant color,** the library actually [calculates a palette of 5 colors](https://github.com/ksubileau/color-thief-php/blob/a1378533433dae824c2e5b70359f8b6ae16b1deb/src/ColorThief/ColorThief.php#L115) and returns the color representing the most pixels among these 5. This is because calculating "_a palette of a single color_" would ultimately result in a simple average of all pixels, which is contrary to the library's initial postulate of using a more complex algorithm than a simple average to determine the dominant color, considering that this is not a good way to define it. 
The number 5 is chosen here in a relatively arbitrary way, as a good balance between a too small number that would approach the result of a simple average that we want to avoid and a too large number that would scatter the pixel colors in too many different computed colors and would not allow to determine a single truly dominant color. 
This also explains why the dominant color is present among a palette of 5 colors but not for another number of colors, as said by @romanzks. 
If you really need to have both a palette of N colors (with N different from 5) AND a single dominant color that MUST be part of the palette, you can calculate the palette first and then extract the first color of the set as the dominant, as the getColor method does on a 5-color basis, but keep in mind that depending on the number of colors requested for your palette, this may affect the actual "dominant" character of the single color you extract. It may be better to accept that the single dominant color is not part of the dominant color palette to get a more accurate single dominant color.

This is one way of defining what "dominant colors in an image" means, as not being a simple ordered sorting of actual colors present in the image but rather a set of similar colors representative of all those present in the source image, trying to better match the perception of a human eye. It is also a method that can be used by image editing software to determine the color palette to use when saving an image in GIF format with a palette limited to 16, 32, ... or 256 colors

You may search about the "Median Cut algorithm" on the Internet if you'd like a more detailed understanding of how it works and determine if it can actually suit your needs or not ([here](https://gowtham000.hashnode.dev/median-cut-a-popular-colour-quantization-strategy) or [there](https://muthu.co/reducing-the-number-of-colors-of-an-image-using-median-cut-algorithm/) for example).
